name: friflex_api
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  google_fonts: ^6.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
#  firebase_database: ^11.1.2
#  firebase_auth: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/12x12
    - assets/icons/16x16
    - assets/icons/20x20
    - assets/icons/24x24
