// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZKBqMP9GH_z01s8pamErX9cPcXok37g',
    appId: '1:1075045396500:web:532fb900152835b1cfb701',
    messagingSenderId: '1075045396500',
    projectId: 'friflex-api-meetup',
    authDomain: 'friflex-api-meetup.firebaseapp.com',
    databaseURL: 'https://friflex-api-meetup-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'friflex-api-meetup.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSUFzR_EpTBgh26mpD5C_zOoe8ZzhoRg',
    appId: '1:1075045396500:ios:68310079874e3ddccfb701',
    messagingSenderId: '1075045396500',
    projectId: 'friflex-api-meetup',
    databaseURL: 'https://friflex-api-meetup-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'friflex-api-meetup.appspot.com',
    iosBundleId: 'com.friflex.api.friflexApi',
  );
}
